import React, { useEffect, useState } from "react";
import { api } from "../api.js";

export default function Grammar({ session }) {
  const [topics, setTopics] = useState(null);
  const [selected, setSelected] = useState(null);
  const [content, setContent] = useState(null);
  const [loadingTopics, setLoadingTopics] = useState(false);
  const [loadingContent, setLoadingContent] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoadingTopics(true);
    setError(null);
    api
      .grammarTopics(session.user_id)
      .then((res) => {
        if (!cancelled) setTopics(res.topics);
      })
      .catch((e) => {
        if (!cancelled) setError(e.message || String(e));
      })
      .finally(() => {
        if (!cancelled) setLoadingTopics(false);
      });
    return () => {
      cancelled = true;
    };
  }, [session.user_id]);

  const openTopic = async (topic) => {
    setSelected(topic);
    setContent(null);
    setLoadingContent(true);
    setError(null);
    try {
      const c = await api.grammarContent(session.user_id, topic.topic);
      setContent(c);
    } catch (e) {
      setError(e.message || String(e));
    } finally {
      setLoadingContent(false);
    }
  };

  if (selected) {
    return (
      <div className="panel">
        <button className="btn btn-ghost" onClick={() => { setSelected(null); setContent(null); }}>
          ← All topics
        </button>
        <h2 style={{ marginTop: 16 }}>{selected.topic}</h2>
        <p className="lead">{selected.description}</p>

        {error && <div className="error-banner">{error}</div>}

        {loadingContent && (
          <p>
            <span className="spinner" /> Generating exercises with your vocabulary…
          </p>
        )}

        {content && (
          <>
            <h3>Rule</h3>
            <p>{content.rule}</p>

            <h3>Scheme</h3>
            <div className="scheme">{content.scheme}</div>

            <h3>Exercises</h3>
            <ol className="exercise-list">
              {content.sentences.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ol>
          </>
        )}
      </div>
    );
  }

  return (
    <div className="panel">
      <h2>Grammar — {session.target_language}</h2>
      <p className="lead">
        Topics generated by the Grammar Agent. Each topic produces ten exercises
        that exercise your loaded vocabulary.
      </p>

      {error && <div className="error-banner">{error}</div>}

      {loadingTopics && (
        <p>
          <span className="spinner" /> Calling the Grammar Agent…
        </p>
      )}

      {topics && (
        <div className="topic-list">
          {topics.map((t) => (
            <button key={t.topic} className="topic-item" onClick={() => openTopic(t)}>
              <h3>{t.topic}</h3>
              <p>{t.description}</p>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
